describe('Test PlantPage', () => {
  it('Finds page of matched plants', () => {
    cy.visit('http://localhost:3000/matched')
  })
  it('Finds a searched plant', () => {
    cy.get('div')
      .find('input')
      .type('Pilea')
      .type('{enter}')
    cy.url().should('include', '/detail')
    cy.get('div')
      .find('button')
      .click()
    cy.url().should('include', '/matched')
  })
  it('Click on PlantImg opens detail for this plant', () => {
    cy.get('a>img:first').click()
    cy.url().should('include', '/detail')
    cy.get('div')
      .find('button')
      .click()
    cy.url().should('include', '/matched')
  })
  it('Write note in card', () => {
    cy.get('svg:first').click()
    cy.get('form textarea').type('Dies ist eine Test-Notiz')
    cy.get('form')
      .find('svg')
      .click()
  })
  it('Bookmark card', () => {
    cy.get('section header:first div')
      .find('img')
      .click()
      .should('have.css', 'color')
      .and('eq', 'rgb(54, 120, 96)')
  })
  it('Click on Fav-Button brings you to FavPage', () => {
    cy.get('div>div>a:last').click()
    cy.url().should('include', '/favourite')
  })
})
