import testPicture from './img/testPicture1.jpg'
import uid from 'uid'

const plantObjects = [
  {
    title: 'test1',
    img: testPicture,
    id: uid(),
    isBookmarked: false,
    tagList: [
      'room',
      'not-dark',
      'moist',
      'easy',
      'not-big',
      'wide',
      'toxic',
      'not-winter',
      'allergenic',
    ],
  },
  {
    title: 'test2',
    img: testPicture,
    id: uid(),
    isBookmarked: false,
    tagList: [
      'room',
      'not-dark',
      'moist',
      'not-easy',
      'big',
      'wide',
      'not-toxic',
      'winter',
      'not-allergenic',
    ],
  },
  {
    title: 'test3',
    img: testPicture,
    id: uid(),
    isBookmarked: false,
    tagList: [
      'not-room',
      'not-dark',
      'not-moist',
      'easy',
      'not-big',
      'not-wide',
      'not-toxic',
      'winter',
      'not-allergenic',
    ],
  },
  {
    title: 'test4',
    img: testPicture,
    id: uid(),
    isBookmarked: false,
    tagList: [
      'room',
      'dark',
      'not-moist',
      'easy',
      'big',
      'wide',
      'toxic',
      'not-winter',
      'allergenic',
    ],
  },
  {
    title: 'test5',
    img: testPicture,
    id: uid(),
    isBookmarked: false,
    tagList: [
      'not-room',
      'dark',
      'moist',
      'not-easy',
      'big',
      'wide',
      'not-toxic',
      'not-winter',
      'allergenic',
    ],
  },
]

export default plantObjects
